### ISSUE TITLE
Move to a two-main-column docs page

### ISSUE THREAD

**Issue by piedoom** [amethyst/website#5]
![image](https://user-images.githubusercontent.com/8846211/59728533-1c105b00-9200-11e9-8484-007b80bcd203.png)

I was a little disoriented at first from the progression, being Stable -> Previous -> Master. As we continue to add more releases, we will continue to have a greater separation between stable and master. We also don't want to put master at the top, since we want to encourage users to use stable. Instead, we can put them in a special row with two columns.

![image](https://user-images.githubusercontent.com/8846211/59728698-c5575100-9200-11e9-8c47-7be5f901c599.png)

If you agree, I can also implement this.

**Comment by happenslol** [comment]
I like this a lot! I'd super appreciate it if you could implement it. Here's a few pointer as to how you can go about it:

* The documentation page is rendered through the dynamic `page.jsx` template. Any instance of the `Page` type in prismic will generate one of these.
* Every section of the page is a `slice`, which is basically a block of content that will have specific styling. For this instance, we'd add a slice with the type `multi-column`.
* I'd suggest taking the `page.jsx` template and creating a simple mockup with static content, above or below the other content. When you're done with that, just hit me up and I'll add the slice type on prismic, or I'll show you how you can do it yourself =)

**Comment by Moxinilian** [comment]
We used to have that sort of layout before, and it had the downside of encouraging the use of master and therefore increasing discrepancy around docs, community work and what people used.

**Comment by piedoom** [comment]
IMO, there really shouldn't be an issue with using master. I use it for my own projects, and since Amethyst is changing constantly, I prefer to make small incremental changes than a huge one (e.g. 0.10.0 to 0.11.0 takes a *lot* of work). As long as the limitations/possible difficulties are clear, I'd say it's fine. I'd actually be curious to see what community members use, be it .10, .11, or master.

We could additionally make the master branch smaller, but I still think it needs to be separate in some way. Putting the technically latest stuff at the bottom is not intuitive, especially when we have many releases.

**Comment by happenslol** [comment]
Two column layout has been implemented, so I'm closing this
