### ISSUE TITLE
Update the Roadmap

### ISSUE THREAD

**Issue by veigaribo** [amethyst/website#7]
When I first found Amethyst, in mid-2019, I used to regularly check [the Roadmap](https://amethyst.rs/roadmap) to see if any of the goals there had been accomplished, mainly the "iOS and Android Support" one. I wanted to use the engine, but had not really a reason to, as my goal at that time was to make mobile games.

I started to realize that the website wasn't cared of that much, and now it seems quite obsolete with those old goals there (which I have no idea if they were done or not, because I did not get involved with the project).

Maybe you/we could update that, possibily showing what has already been done, so that new people may see a reason to use Amethyst, instead of a reason to not to, by thinking it has been abandoned or something like that.

**Comment by CleanCut** [comment]
That is an excellent idea. I would also love to see regular updates on the web site. Perhaps I can help with that.

**Comment by veigaribo** [comment]
Hm actually, it seems [the Roadmap](https://amethyst.rs/roadmap) has been updated since I initially opened this issue...

In the hosted website it says that "more will be added later", so I suppose this is something people are already working on.

Guess it would be appropriate to close this issue, then?

**Comment by CleanCut** [comment]
Yes, I think this can be closed.  We've got active roadmap-type discussions going on in the forum [here](https://community.amethyst.rs/t/a-fresh-step-forward-proposal-for-future-development-and-collaboration/1614?u=cleancut) and [here](https://community.amethyst.rs/t/a-fresh-step-forward-p2-the-engine/1615?u=cleancut)
